version: "3.8"

services:
  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./dist:/opt/airflow/dist
      - ./package.json:/opt/airflow/package.json
      - workflow_db:/opt/airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: api-server
    ports:
      - "9090:8080"

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./dist:/opt/airflow/dist
      - ./package.json:/opt/airflow/package.json
      - workflow_db:/opt/airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: scheduler
    depends_on:
      - airflow-apiserver

  lb4-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    command: node dist/index.js

volumes:
  workflow_db:
