version: "3.8"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="     # real Fernet key
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # must be identical across components that validate tokens
      AIRFLOW__API_AUTH__JWT_SECRET: "idp_workflow_project"                 # <-- important (name)
      # auto create admin (Airflow 3.x)
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
      _AIRFLOW_WWW_USER_FIRSTNAME: "Admin"
      _AIRFLOW_WWW_USER_LASTNAME: "User"
      _AIRFLOW_WWW_USER_EMAIL: "admin@test.com"
    command: bash -c "airflow db migrate"
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "9090:8080"   # UI/API
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="
      AIRFLOW__API_AUTH__JWT_SECRET: "idp_workflow_project"                     # same secret
      AIRFLOW__WEBSERVER__BASE_URL: "http://31.97.224.212:9090"                 # your public UI URL

      # Logging: apiserver must know where scheduler exposes the log server
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_ENABLED: "True"
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_HOST: "airflow-scheduler"             # must be resolvable service name
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: "8793"
      AIRFLOW__CORE__HOSTNAME_CALLABLE: "socket.gethostname"
    command: api-server
    volumes:
      - ./src/dags:/opt/airflow/dags

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8793:8793"   # expose log server port so apiserver can fetch logs
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_ENABLED: "True"
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_HOST: "airflow-scheduler"
      AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: "8793"
      AIRFLOW__CORE__HOSTNAME_CALLABLE: "socket.gethostname"
    command: scheduler
    volumes:
      - ./src/dags:/opt/airflow/dags

  airflow-dag-processor:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="
    command: dag-processor
    volumes:
      - ./src/dags:/opt/airflow/dags

  lb4-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    command: node dist/index.js

volumes:
  postgres_db:
