version: "3.8"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="
      AIRFLOW__API_AUTH__JWT_SECRET_KEY: "idp_workflow_project"

      # try to auto-create admin user when supported
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
      _AIRFLOW_WWW_USER_FIRSTNAME: "Admin"
      _AIRFLOW_WWW_USER_LASTNAME: "User"
      _AIRFLOW_WWW_USER_EMAIL: "admin@test.com"

      # Logging config: use local logs (no remote log server)
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__CORE__DAG_BAG_USE_BUNDLES: "False"
    command: bash -c "airflow db migrate"
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    restart: "no"

  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="
      AIRFLOW__API_AUTH__JWT_SECRET_KEY: "idp_workflow_project"

      # External URL for UI (optional - change to your server IP / host if needed)
      AIRFLOW__WEBSERVER__BASE_URL: "http://31.97.224.212:9090"

      # Ensure API server reads logs from shared volume (no log server)
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__CORE__DAG_BAG_USE_BUNDLES: "False"
    command: api-server
    ports:
      - "9090:8080" # UI + API
    volumes:
      - ./src/dags:/opt/airflow/dags:ro
      - ./logs:/opt/airflow/logs
    restart: always

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__CORE__DAG_BAG_USE_BUNDLES: "False"
    command: scheduler
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    restart: always

  airflow-dag-processor:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "S8p2L4l6g9VQe2pXjC5y7GkWbVtmJf7y2Xqj0CN4UJ0="
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__CORE__DAG_BAG_USE_BUNDLES: "False"
    command: dag-processor
    volumes:
      - ./src/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    restart: always

  lb4-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    command: node dist/index.js
    restart: always

volumes:
  postgres_db:
