version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 5

airflow-init:
  build:
    context: .
    dockerfile: Dockerfile.airflow
  depends_on:
    postgres:
      condition: service_healthy
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: "idp_workflow_project"
    AIRFLOW__API_AUTH__JWT_SECRET: "idp_workflow_project"

    # Auto-create admin user (Airflow 3.x)
    _AIRFLOW_WWW_USER_CREATE: "true"
    _AIRFLOW_WWW_USER_USERNAME: "admin"
    _AIRFLOW_WWW_USER_PASSWORD: "admin"
    _AIRFLOW_WWW_USER_EMAIL: "admin@test.com"
    _AIRFLOW_WWW_USER_FIRSTNAME: "admin"
    _AIRFLOW_WWW_USER_LASTNAME: "admin"

  command: >
    bash -c "
      airflow db migrate
    "
  volumes:
    - ./src/dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins

  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "REPLACE_WITH_REAL_FERNET_KEY"
      AIRFLOW__API_AUTH__JWT_SECRET: "idp_workflow_project"
    volumes:
      - ./src/dags:/opt/airflow/dags
    command: api-server
    ports:
      - "9090:8080"

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "REPLACE_WITH_REAL_FERNET_KEY"
      AIRFLOW__API_AUTH__JWT_SECRET: "idp_workflow_project"
    volumes:
      - ./src/dags:/opt/airflow/dags
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "REPLACE_WITH_REAL_FERNET_KEY"
    volumes:
      - ./src/dags:/opt/airflow/dags
    command: scheduler

  lb4-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    command: node dist/index.js

volumes:
  postgres_db:
